function fsc_fields = sg_calculate_fsc_get_fields()
%% sg_calculate_fsc_get_fields
% Return the fields for the sg_calculate_FSC inputs.
%
% WW 05-2024

%% Fields

fsc_fields = {'refA_name', 'str', [];...
              'refB_name', 'str', [];...
              'mask_name', 'str', 'none';...
              'symmetry', 'str', 'C1';...
              'pixelsize', 'num', [];... 
              'ref_avg_name', 'str', 'no_output_ref';...
              'flip_density', 'boo', 'true';...
              'apply_fom', 'boo', 'true';...
              'bfactor', 'num', '0';...
              'fsc_thresh', 'num', '0.143';...
              'edge_smooth', 'num', '3';...
              'x_label', 'num', '0';...
              'res_label', 'num', '[32,16,8,6,4,2]';...
              'plot_diagnostic', 'boo', 'false';...
              'plot_sharp', 'boo', 'false';...
              'fourier_cutoff', 'num', '5';...
              'n_repeats', 'num', '10';...
              };
              

        
end
