function ordered_fields = sg_get_ordered_subtomo_input_fields()

ordered_fields = {'completed_ali', 'boo';
                  'completed_p_avg', 'boo';
                  'completed_f_avg', 'boo';
                  'iteration', 'num';
                  'subtomo_mode', 'str';
                  'rootdir', 'str';
                  'tempdir', 'str';
                  'commdir', 'str';
                  'rawdir',  'str';
                  'refdir',  'str';
                  'maskdir',  'str';
                  'listdir',  'str';
                  'fscdir',  'str';
                  'specdir', 'str';
                  'subtomodir'  'str';
                  'metadir', 'str';
                  'motl_name', 'str';
                  'wedgelist_name', 'str';
                  'binning', 'num';
                  'ref_name', 'str';
                  'subtomo_name', 'str';
                  'mask_name', 'str';
                  'ccmask_name', 'str';
                  'ali_reffilter_name', 'str';
                  'ali_particlefilter_name', 'str';
                  'avg_reffilter_name', 'str';
                  'avg_particlefilter_name', 'str';
                  'reffiltertype', 'str';
                  'particlefiltertype', 'str';
                  'ps_name', 'str';
                  'amp_name', 'str';
                  'specmask_name', 'str';
                  'search_mode', 'str';
                  'search_type', 'str';
                  'euler_axes', 'str';
                  'euler_1_incr', 'num';
                  'euler_1_iter', 'num';
                  'euler_2_incr', 'num';
                  'euler_2_iter', 'num';
                  'euler_3_incr', 'num';
                  'euler_3_iter', 'num';
                  'angincr', 'num';
                  'angiter', 'num';
                  'phi_angincr', 'num';
                  'phi_angiter', 'num';
                  'cone_search_type', 'str';
                  'apply_laplacian', 'boo';
                  'scoring_fcn', 'str';
                  'lp_rad', 'num';
                  'lp_sigma', 'num';
                  'hp_rad', 'num';
                  'hp_sigma', 'num';
                  'calc_exp', 'boo';
                  'calc_ctf', 'boo';
                  'cos_weight', 'num';
                  'score_weight', 'num';
                  'symmetry', 'str';
                  'score_thresh', 'num';
                  'subset', 'num';
                  'avg_mode','str';
                  'ignore_halfsets','boo';
                  'temperature','num';
                  'rot_mode','str';
                  'fthresh', 'num';
                  'avg_ss','boo';};
