function header_fields = sg_default_mrc_header_fields()
%% sg_default_mrc_header_fields
% A function to return default .mrc header fields and values in a cell
% array.
%
% WW 06-2018

%% Header

header_fields = {'nx',          0;...
                 'ny',          0;...
                 'nz',          0;...
                 'mode',        2;...
                 'nxstart',     0;...
                 'nystart',     0;...
                 'nzstart',     0;...
                 'mx',          0;...
                 'my',          0;...
                 'mz',          0;...
                 'xlen',        0;...
                 'ylen',        0;...
                 'zlen',        0;...
                 'alpha',       90;...
                 'beta',        90;...
                 'gamma',       90;...
                 'mapc',        1;...
                 'mapr',        2;...
                 'maps',        3;...
                 'amin',        0;...
                 'amax',        0;...
                 'amean',       0;...
                 'ispg',        0;...
                 'nsymbt',      0;...
                 'next',        0;...
                 'creatid',     0;...
                 'nint',        0;...
                 'nreal',       0;...
                 'idtype',      0;...
                 'lens',        0;...
                 'nd1',         0;...
                 'nd2',         0;...
                 'vd1',         0;...
                 'vd2',         0;...
                 'tiltangles',  [0,0,0,0,0,0];...
                 'xorg',        0;...
                 'yorg',        0;...
                 'zorg',        0;...
                 'cmap',        ('MAP ')';...
                 'stamp',       ('D   ')';...
                 'rms',         -1;...
                 'nlabl',       0;...
                 'labl',        [];...
                 };