function rot_mat = sg_euler2matrix(phi,psi,the)
%% sg_euler2matrix
% A function convert a set of euler angles to a rotation matrix. This
% assumes the AV3 convention, i.e. phi-the-psi rotation is an Z-X-Z
% rotation.
%
% WW 08-2016

%% Calculate rotation matrix
rot_mat = [cosd(psi) -sind(psi) 0;...
           sind(psi)  cosd(psi) 0;...
           0          0         1]*...
           ...
          [1          0         0;...
           0          cosd(the) -sind(the);...
           0          sind(the) cosd(the)]*...
           ...           
          [cosd(phi) -sind(phi) 0;...
           sind(phi) cosd(phi)  0;...
           0         0          1];
